"""Public case studies: functional abstractions and confirmed contribution scope."""

PROJECTS = {
 'en': [
  dict(
   name='Stereo-led perception', title='From model outputs to a useful scene representation.',
   summary='Co-designing stereo-led perception for plane structure, obstacle geometry and carpet recognition.', topic='FRAMEWORK CO-DESIGN',
   lead='Stereo-led multi-sensor perception connects model outputs to robot-usable geometry and semantics. I co-designed its processing framework and developed and optimized several capabilities within it.',
   role='Shared framework design; ground reference, thin obstacles, carpet recognition and runtime optimization.',
   context='Multi-sensor perception in consumer robotics.',
   overview_title='A framework that connects complementary capabilities.',
   overview=['Model outputs provide complementary information about depth and object identity. The framework turns them into spatial representations, combining geometric and semantic reasoning with ground understanding, obstacle representation and carpet recognition.'],
   system_title='Functional scope, from observations to scene understanding.',
   system_intro='This view groups capabilities by their responsibilities. It shows the scope of the system and my contribution, rather than an execution sequence.',
   groups=[
    ('Observation context','System context',['Depth observations','Visual semantics','Motion context']),
    ('Scene understanding','Shared design',['Geometric processing','Semantic interpretation']),
    ('Perception functions','Design & development',['Plane structure','Obstacle geometry','Thin obstacles','Carpet recognition']),
    ('Robot-facing output','System output',['Spatial representation','Scene attributes'])],
   contribution_title='Framework design and capabilities developed within it.',
   contributions=[
    ('Shared framework design','Co-designed','Connected geometric processing, semantic interpretation and perception functions within a consistent output framework.'),
    ('Ground reference & geometric consistency','Introduced','Added plane-structure understanding to support online calibration and point-cloud correction during bumpy motion.'),
    ('Thin-obstacle representation','Developed','Improved the spatial representation of small obstacles when individual observations provide limited geometric support.'),
    ('Carpet recognition','Developed','Combined complementary evidence to make carpet perception more useful when individual observations are uncertain.'),
    ('Classification & runtime','Adapted & optimized','Adapted an existing classification capability and optimized processing cost within the stereo framework.')],
   choices_title='Consistency across capabilities, within a runtime budget.',
   choices=[('Keep responsibilities distinct','Ground-reference reasoning supports geometric consistency; carpet recognition describes a different scene property. Clear responsibilities make their outputs easier to integrate.'),('Balance representation and processing cost','The framework must provide useful spatial information while fitting a practical runtime budget. Integration and optimization are part of delivering each capability.')],
   result_title='Geometric consistency and obstacle representation',
   result=['The framework gains support for online calibration and point-cloud correction during bumpy motion, more useful thin-obstacle geometry, and carpet recognition from complementary evidence. Adapted classification and runtime optimization support robot deployment.'],
   limits='Scene interpretation remains dependent on the quality and availability of observations. Constructed representations should retain the distinction between observed evidence and inference.',
   demo_title='A closer look · thin-obstacle representation',
   demo_intro='The example below illustrates one capability within the framework: representing a small obstacle when the available spatial observations are sparse.',
   caption='Top view. Surface observations contain gaps and occlusion. Amber dashes illustrate a thin-obstacle representation.', panels=[]),
  dict(
   name='LiDAR-led perception', title='Evolving perception for production outdoor robots.',
   summary='Evolving an established outdoor perception framework, with height structure, target tracking and production reuse.', topic='PRODUCTION & EVOLUTION',
   lead='The project builds on an established LiDAR-led multi-sensor framework for outdoor robots. My contribution spans implementation and architecture evolution, including leading the introduction of dynamic-target tracking.',
   role='Framework implementation and evolution; height-related scene handling; tracking led by me.',
   context='Outdoor perception for production robotic lawn mowers.',
   overview_title='From an initial framework to sustained production work.',
   overview=['Outdoor environments include overhanging obstacles and moving targets that a flat, static description cannot fully capture. The initial framework was established before I joined; the work here extends its spatial and temporal understanding through production development.'],
   system_title='Spatial understanding and temporal continuity.',
   system_intro='The functional view shows the breadth of the system. It groups responsibilities without reproducing internal module boundaries or processing order.',
   groups=[
    ('Observation context','System context',['Range observations','Additional observations','Motion context']),
    ('Environment understanding','Framework evolution',['Spatial representation','Height structure']),
    ('Target understanding','Tracking: led introduction',['Target interpretation','Temporal continuity']),
    ('Robot-facing output','System output',['Environment information','Target states'])],
   contribution_title='Production integration, spatial structure and dynamic targets.',
   contributions=[
    ('Framework implementation & evolution','Contributed','Connected perception capabilities, resolved deployment issues and participated in continued development of the framework.'),
    ('Height-related scene handling','Developed & maintained','Improved handling of height structure and overhanging obstacles in outdoor environments.'),
    ('Dynamic-target tracking','Led introduction','Introduced tracking to relate observations over time and provide persistent descriptions of moving targets.')],
   choices_title='Preserve meaningful structure across space and time.',
   choices=[('A footprint is only part of the scene','Similar plan-view footprints can correspond to different vertical structures. Height information matters when interpreting outdoor obstacles.'),('Target motion and robot motion interact','Changing viewpoint and temporary occlusion complicate continuity. Motion context and temporal information help make successive observations interpretable.')],
   result_title='Production deployment and reuse across robot platforms.',
   result=['The system adds height-aware scene handling and persistent descriptions of dynamic targets. The framework is used in production and reused across multiple robotic lawn-mower platforms.'],
   limits='Occlusion and ambiguous observations can still complicate target interpretation. A persistent state and a current observation carry different kinds of information.',
   demo_title='A closer look · target continuity',
   demo_intro='This independent scene illustrates how discrete observations and a target’s history describe different aspects of a changing environment.',
   caption='Angular samples stop at the first surface. The dotted track segment illustrates temporal continuity during occlusion.', panels=[]),
  dict(
   name='Collision-engine integration', title='Connecting collision-query capabilities to an existing engine.',
   summary='Extending collision-query capabilities through geometry, interface and processing integration.', topic='ENGINE INTEGRATION',
   lead='This project extends an existing physics-simulation engine’s collision-query pipeline, connecting additional query capabilities to its geometry representations and interfaces.',
   role='Collision-pipeline extension design, algorithm integration and engine adaptation.',
   context='Research development within an existing physics-simulation engine.',
   overview_title='An engine extension needs more than an isolated algorithm.',
   overview=['The engine’s limited collision-query options needed expansion across broadphase, midphase and narrowphase. New algorithms had to work with the host engine’s existing geometry and stage interfaces.'],
   system_title='Query capabilities within their engine context.',
   system_intro='The diagram separates query responsibilities from the integration work that makes them usable within an existing engine.',
   groups=[
    ('Engine context','Existing foundation',['Geometry representations','Query interfaces']),
    ('Query capabilities','Added capabilities',['Candidate filtering · SAP','Spatial hierarchy · BVH','Convex query · GJK']),
    ('Integration work','Designed & integrated',['Geometry adaptation','Stage interfaces','Algorithm options']),
    ('Engine-facing result','System output',['Collision-query results','Selectable capabilities'])],
   contribution_title='Algorithm capabilities connected to the host engine.',
   contributions=[
    ('Query-stage extensions','Designed & integrated','Added SAP broadphase, a BVH midphase and GJK convex-query capabilities across the collision pipeline.'),
    ('Geometry & interface adaptation','Implemented','Adapted inputs, outputs and stage interfaces to the host engine’s existing representations and data flow.'),
    ('Preserved algorithm choices','Integrated','Made the additions available alongside existing capabilities, including SAT, so query options could coexist.')],
   choices_title='Clear stage responsibilities and compatible interfaces.',
   choices=[('Different stages answer different questions','Candidate filtering, spatial hierarchy queries and convex queries operate at different levels. Their results need compatible meanings at stage boundaries.'),('Extend the engine’s available choices','New query capabilities joined the existing options. Integration made those options usable within the same engine context.')],
   result_title='Additional collision-query options in the existing engine.',
   result=['SAP, BVH and GJK became usable query options within the existing engine. The original algorithms, including SAT, remained available alongside the additions.'],
   limits='Candidate filtering is conservative, and convex queries have a specific geometric scope. Algorithm suitability depends on the query and scene.',
   demo_title='A closer look · query-stage responsibilities',
   demo_intro='The three panels illustrate the different questions asked by the query stages. They are explanatory geometry, independent of the host engine.',
   caption='Illustrative bounds and convex shapes show candidate filtering, hierarchy queries and a finer geometric query.',
   panels=[('Broadphase · SAP','Bounds identify potential object pairs.'),('Midphase · BVH','Hierarchical bounds restrict the geometry to examine.'),('Narrowphase · GJK','Convex geometry supports a finer query.')]),
  dict(
   name='Video-based climbing analysis', title='From climbing video to interpretable movement analysis.',
   summary='Connecting climbing video to trajectory, velocity and joint-angle analysis through a complete research pipeline.', topic='RESEARCH PIPELINE',
   lead='The monocular-video research pipeline connects hold detection, human pose estimation and spatial mapping to trajectory, velocity and joint-angle analysis.',
   role='Pipeline design and implementation; visual-perception integration, spatial mapping, movement analysis and evaluation.',
   context='Master’s research · Robotic Systems Engineering · RWTH Aachen University.',
   overview_title='Connect the observations to the quantities being analysed.',
   overview=['Competition footage contains both athlete movement and changing camera framing. The research covers the video-to-analysis pipeline, placing observations in a common wall reference and evaluating the resulting movement features.'],
   system_title='The complete research pipeline.',
   system_intro='Hold observations establish the wall reference. Pose observations describe the athlete. Spatial mapping connects them before movement features are analysed.',
   research_nodes=[('video','Video preparation','Selected & prepared frames'),('holds','Hold detection','Visible wall features'),('matching','Frame–template matching','Wall-reference alignment'),('pose','Human pose estimation','Athlete observations'),('mapping','Coordinate mapping','Common spatial reference'),('analysis','Movement analysis','Trajectory, velocity & joint angles')],
   contribution_title='Visual perception, spatial mapping and analysis as one system.',
   contributions=[
    ('Pipeline design & visual perception','Designed & implemented','Prepared the video data and connected hold detection and human pose estimation to the downstream analysis.'),
    ('Frame alignment & coordinate mapping','Developed','Related changing visible hold subsets to a fixed wall template and mapped observations into a common reference.'),
    ('Movement analysis','Implemented','Connected aligned observations to trajectory, velocity and joint-angle analysis.'),
    ('Experimental evaluation','Evaluated','Examined the perception, spatial-mapping and movement-analysis stages, including their practical limitations.')],
   choices_title='Use a common reference and interpret each output carefully.',
   choices=[('Separate changing framing from movement','The camera window changes while wall holds remain fixed. A common wall reference makes observations across frames comparable.'),('Analyse the pipeline at several levels','Perception quality, mapping consistency and movement interpretation each affect the final result. The research evaluated those stages as connected parts of the system.')],
   result_title='Trajectory, velocity and joint-angle analysis from video.',
   result=['The implemented workflow produces trajectories, velocity profiles and joint-angle analysis from climbing video. Mapping observations to a common reference makes them comparable across changing camera frames.'],
   limits='A wall reference and monocular pose estimates do not recover complete metric three-dimensional motion. Template dependence and depth ambiguity remain relevant to interpretation.',
   demo_title='A closer look · spatial mapping within the pipeline',
   demo_intro='This example focuses on the mapping stage: a moving observation window reveals changing subsets of fixed wall holds, followed by movement interpretation in the wall reference.',
   caption='Wall holds remain fixed while the window moves upward. The curve shows speed derived from the same synthetic trajectory in normalized wall coordinates; the horizontal axis is synthetic time.',
   panels=[('Current frame','Only holds inside the observation window are visible.'),('Fixed wall template','The frame moves upward; wall holds stay fixed.'),('Mapped movement','Trajectory and speed share the wall reference.')]),
 ],
 'zh': [
  dict(
   name='双目融合感知', title='从模型输出到机器人可用的环境表示。',
   summary='共同设计双目融合感知框架，覆盖平面结构理解、障碍物表示与地毯识别。', topic='框架共建',
   lead='以双目为主要观测来源的多传感器感知，将模型输出转化为机器人可用的几何与语义信息。我参与处理框架的共同设计，以及多项功能的开发与优化。',
   role='框架共同设计；平面参考、细小障碍物、地毯识别与运行优化。', context='消费机器人中的多传感器融合感知。',
   overview_title='将互补能力连接成完整的感知框架。',
   overview=['模型输出提供深度与物体类别等互补信息。处理框架将这些信息转化为空间表示，连接几何与语义理解、地面结构分析、障碍物表示和地毯识别。'],
   system_title='从观测到场景理解的功能范围。',
   system_intro='按功能职责组织系统能力，展示系统范围与我的参与，不表示内部执行顺序。',
   groups=[
    ('观测与上下文','系统背景',['深度观测','视觉语义','运动上下文']),
    ('场景理解','共同设计',['几何处理','语义解释']),
    ('感知功能','设计与开发',['平面结构','障碍物几何','细小障碍物','地毯识别']),
    ('面向机器人的输出','系统输出',['空间表示','场景属性'])],
   contribution_title='框架设计，以及其中的能力建设。',
   contributions=[
    ('整体处理框架','共同设计','连接几何处理、语义理解与各项感知功能，形成一致的感知输出。'),
    ('平面参考与几何一致性','引入','增加平面结构理解，支持在线标定与颠簸状态下的点云校正。'),
    ('细小障碍物表示','开发','在观测提供的几何支撑有限时，改善细小障碍物的空间表示。'),
    ('地毯识别','开发','利用互补信息，改善单类观测不确定时地毯结果的可用性。'),
    ('分类能力与运行效率','适配与优化','将已有分类能力适配到双目框架，并优化处理开销。')],
   choices_title='让多项能力保持一致，并满足运行预算。',
   choices=[('明确不同能力的职责','平面参考支持几何一致性，地毯识别描述另一类场景属性。清楚的职责划分有助于将不同输出连接到整体框架。'),('兼顾空间表示与处理成本','系统需要提供可用的空间信息，也需要适应实际运行预算。能力集成和耗时优化共同决定工程可用性。')],
   result_title='几何一致性与障碍物表示',
   result=['框架增加了在线标定与颠簸点云校正的支持，改善细小障碍物的几何表示，并通过互补信息实现地毯识别。分类能力适配与耗时优化支撑机器人端部署。'],
   limits='场景理解仍依赖观测质量与有效信息。构建出的表示需要区分观测证据与推断部分。',
   demo_title='局部展开 · 细小障碍物表示',
   demo_intro='下面展示框架中的一项能力：当有效空间观测较为稀疏时，如何理解细小障碍物的表示问题。',
   caption='俯视图。表面观测存在缺失与遮挡；橙黄色虚线表示细小障碍物几何的示意。', panels=[]),
  dict(
   name='激光雷达融合感知', title='面向量产户外机器人的感知系统演进。',
   summary='参与既有户外感知框架演进，完善高度结构与目标跟踪，支持量产复用。', topic='量产与演进',
   lead='项目基于既有的激光雷达多传感器融合感知框架，服务于户外机器人。我的工作覆盖实现与后续架构演进，并主导引入动态目标跟踪。',
   role='框架实现与演进、高度结构处理；主导引入目标跟踪。', context='量产割草机器人的户外感知。',
   overview_title='从初始框架到持续的量产工程工作。',
   overview=['户外环境中的悬空障碍物和运动目标，难以仅用平面、静态的场景描述。初始框架在我入职前已确定，这里的工作是在量产开发中扩展其空间与时间理解。'],
   system_title='空间理解与时间连续性。',
   system_intro='按职责归纳系统的完整功能范围，不复现内部模块边界或处理顺序。',
   groups=[
    ('观测与上下文','系统背景',['距离观测','其他观测','运动上下文']),
    ('环境理解','框架演进',['空间表示','高度结构']),
    ('目标理解','跟踪：主导引入',['目标解释','时间连续性']),
    ('面向机器人的输出','系统输出',['环境信息','目标状态'])],
   contribution_title='量产集成、空间结构与动态目标。',
   contributions=[
    ('框架实现与演进','参与','连接各项感知能力，处理部署问题，并参与框架的持续开发与演进。'),
    ('高度结构处理','开发与维护','完善户外环境中高度结构与悬空障碍物相关的感知处理。'),
    ('动态目标跟踪','主导引入','增加跨帧观测关联与持续的目标状态描述，扩展对运动目标的理解。')],
   choices_title='同时保留空间结构与时间信息。',
   choices=[('平面投影只描述场景的一部分','相近的俯视投影可能对应不同高度结构。解释户外障碍物时，高度信息具有独立价值。'),('目标运动与机器人运动共同影响观测','视角变化和暂时遮挡会增加连续理解的难度，需要结合运动上下文与时间信息解释相邻观测。')],
   result_title='量产应用与多机型复用。',
   result=['系统增加了高度结构处理与持续的动态目标状态描述。相关框架已用于量产产品，并在多个割草机器人平台上复用。'],
   limits='遮挡与不确定观测仍会影响目标解释。持续的目标状态与当前观测承载不同的信息。',
   demo_title='局部展开 · 目标连续性',
   demo_intro='独立制作的场景展示离散观测与目标历史，分别如何描述持续变化的环境。',
   caption='角度采样在第一处表面停止；虚线轨迹示意遮挡期间的时间连续性。', panels=[]),
  dict(
   name='仿真引擎碰撞检测', title='将碰撞查询能力融入既有仿真引擎。',
   summary='扩展碰撞查询能力，完成几何表示、接口与处理流程的集成。', topic='引擎集成',
   lead='项目扩展既有物理仿真引擎的碰撞查询流程，将新增查询能力接入原有几何表示与接口。',
   role='碰撞流程扩展设计、算法集成与引擎适配。', context='既有物理仿真引擎中的研究开发。',
   overview_title='引擎扩展需要完整的集成工作。',
   overview=['原有碰撞查询选项有限，需要扩展粗检测（Broadphase）、中间阶段（Midphase）与精检测（Narrowphase）。新增算法需与引擎已有的几何表示和阶段接口兼容。'],
   system_title='引擎背景中的查询能力与集成职责。',
   system_intro='区分算法阶段的查询职责，以及让这些能力在既有引擎中可用的集成工作。',
   groups=[
    ('引擎背景','已有基础',['几何表示','查询接口']),
    ('查询能力','新增能力',['候选筛选 · SAP','空间层次查询 · BVH','凸几何查询 · GJK']),
    ('集成工作','设计与集成',['几何适配','阶段接口','算法选项']),
    ('面向引擎的结果','系统输出',['碰撞查询结果','可选查询能力'])],
   contribution_title='将新增查询能力连接到宿主引擎。',
   contributions=[
    ('查询阶段扩展','设计与集成','引入 SAP 粗检测、BVH 中间阶段与 GJK 精检测中的凸几何查询。'),
    ('几何表示与接口适配','实现','将输入输出与阶段接口适配到宿主引擎已有的表示与数据流。'),
    ('保留算法选择','集成','让新增能力与包括 SAT 在内的已有算法并存，形成可选查询路径。')],
   choices_title='明确阶段职责，保持接口兼容。',
   choices=[('不同阶段回答不同问题','候选筛选、空间层次查询和凸几何查询处在不同层次，阶段之间需要一致的结果含义。'),('扩展引擎中的算法选择','新增查询能力与已有选项共同使用。集成工作让这些选择能够在同一引擎背景下工作。')],
   result_title='既有引擎拥有更多可选查询能力。',
   result=['SAP、BVH 和 GJK 成为既有引擎中可用的查询选项。包括 SAT 在内的原有算法仍与新增能力并存。'],
   limits='候选筛选输出保守集合，凸几何查询有明确的几何适用范围。算法选择取决于场景与查询任务。',
   demo_title='局部展开 · 查询阶段的职责',
   demo_intro='三个面板分别展示不同查询阶段回答的问题，使用独立于宿主引擎的解释性几何。',
   caption='用示意包围范围与凸几何解释候选筛选、层次查询和更精细的几何查询。',
   panels=[('粗检测 · SAP','包围范围筛选潜在对象对。'),('中间阶段 · BVH','层次包围结构缩小待检查的几何范围。'),('精检测 · GJK','凸几何支持更精细的查询。')]),
  dict(
   name='视频攀岩运动分析', title='从攀岩视频到可解释的运动分析。',
   summary='通过完整研究流程，将攀岩视频连接到轨迹、速度与关节角分析。', topic='完整研究流程',
   lead='基于单目视频的研究流程，将岩点检测、人体姿态估计与空间映射连接起来，用于轨迹、速度和关节角分析。',
   role='流程设计与实现；视觉感知集成、空间映射、运动分析与实验评价。', context='硕士研究 · 机器人系统工程 · RWTH Aachen University。',
   overview_title='将视觉观测连接到需要分析的运动量。',
   overview=['比赛画面同时包含攀岩者的运动与镜头取景变化。研究覆盖从视频到运动分析的完整流程，将观测映射到统一墙面参考，并评价运动特征的分析结果。'],
   system_title='完整的研究流程。',
   system_intro='岩点观测建立墙面参考，姿态观测描述攀岩者；空间映射将两者连接，再分析运动特征。',
   research_nodes=[('video','视频准备','筛选与整理画面'),('holds','岩点检测','可见墙面特征'),('matching','画面—模板匹配','墙面参考对齐'),('pose','人体姿态估计','攀岩者观测'),('mapping','坐标映射','统一空间参考'),('analysis','运动分析','轨迹、速度与关节角度')],
   contribution_title='将感知、空间映射与分析组织成一个系统。',
   contributions=[
    ('流程设计与视觉感知','设计与实现','准备视频数据，将岩点检测和人体姿态估计连接到后续分析。'),
    ('画面对齐与坐标映射','开发','将变化的可见岩点集合对应到固定墙面模板，并映射到统一参考。'),
    ('运动分析','实现','将对齐后的观测连接到轨迹、速度与关节角度分析。'),
    ('实验评价','评价','分析感知、空间映射和运动分析各阶段的效果与实际限制。')],
   choices_title='统一参考，并理解各阶段输出的含义。',
   choices=[('区分镜头取景变化与运动','岩点固定，变化的是观察窗口。统一墙面参考让不同帧中的观测能够比较。'),('在不同层次评价完整流程','感知质量、映射一致性与运动解释共同影响最终结果。研究将这些阶段作为相互连接的系统进行评价。')],
   result_title='从视频中分析轨迹、速度与关节角。',
   result=['实现的流程能够分析攀岩轨迹、速度变化与关节角度。映射到统一参考后，不同取景画面中的观测可以相互比较。'],
   limits='墙面参考与单目姿态估计不能恢复完整的真实尺度三维运动。模板依赖和深度歧义仍会影响解释。',
   demo_title='局部展开 · 流程中的空间映射',
   demo_intro='这里聚焦空间映射阶段：移动的观察窗口显示固定墙点的不同子集，再将运动放到统一墙面参考下解释。',
   caption='墙面岩点固定，窗口向上移动。曲线表示同一合成轨迹在归一化墙面坐标中的速度，横轴为示意时间。',
   panels=[('当前画面','只显示观察窗口内可见的岩点。'),('固定墙面模板','画面向上移动，岩点位置保持固定。'),('映射后的运动','轨迹与速度使用同一墙面参考。')]),
 ]
}
