"""Public portfolio text. English and Chinese share the same project scope."""
UI = {
 'en': {
  'work':'Work','about':'About','contact':'Contact','skip':'Skip to content','nav':'Main navigation',
  'language':'Language','back':'All selected work','role':'MY ROLE','context':'CONTEXT',
  'previous':'Previous case','next':'Next case','read':'Read case study','problem':'Project scope',
  'method':'Functional overview','choices':'Engineering considerations','result':'Engineering outcome',
  'demo':'Explore the concept','synthetic':'Synthetic illustration',
  'notice':'Functional views regroup responsibilities rather than reproduce internal implementation. Animations and illustrative geometry are independently created using synthetic data, not product recordings or measured results.',
  'play':'Play','pause':'Pause','time':'Demonstration time','layers':'Visualization layers',
  'points':'Observations','geometry':'Geometry','returns':'Returns','rays':'Sampled rays','tracks':'Track',
  'hero_role':'Perception Algorithm Engineer','hero_title':'From observations<br>to <span>geometry.</span>',
  'hero_intro':'I’m Merci, a perception engineer working across system design, implementation and deployment—turning imperfect observations into useful spatial understanding.',
  'explore':'Explore selected work','github':'GitHub profile','hero_visual':'Scene geometry','hero_bottom':'Observations → representation',
  'strip':['Consumer robotics','Multi-sensor fusion','C++ implementation'],
  'selected':'Selected work / 01—04','work_title':'Engineering in practice.',
  'work_intro':'Four systems, their engineering context and my contribution.',
  'about_title':'Perception engineer.<br>Robotics background.',
  'about_p1':'Currently working in consumer robotics on multi-sensor perception led by stereo or LiDAR observations. My work spans framework co-design, model post-processing, spatial understanding, tracking and efficient C++ deployment.',
  'about_p2':'M.Sc. in <b>Robotic Systems Engineering</b> from <b>RWTH Aachen University</b>, with earlier research in collision-engine integration and vision-based climbing analysis.',
  'about_extra':'Additional research: a small neural-network surrogate for manufacturing simulation, paired with an interactive interface.',
  'toolkit':[('Implementation','C++ · Python · CMake<br>Profiling & runtime optimization'),('Perception','OpenCV · Point clouds<br>Geometry, semantics & tracking'),('Simulation','Collision detection<br>Spatial hierarchies & integration')],
  'contact_title':'Let’s talk engineering.','contact_copy':'Perception, geometry and systems that work in practice.',
  'footer':'Merci · Perception & simulation','email':'Email',
  'notfound':'Page not found.','return':'Return to the portfolio',
 },
 'zh': {
  'work':'项目','about':'关于','contact':'联系','skip':'跳到正文','nav':'主导航',
  'language':'语言','back':'查看全部项目','role':'我的职责','context':'项目背景',
  'previous':'上一个案例','next':'下一个案例','read':'阅读案例','problem':'项目范围',
  'method':'功能概览','choices':'工程思考','result':'工程成果',
  'demo':'交互示意','synthetic':'合成示意',
  'notice':'功能图按职责抽象重组，不对应内部实现。动画与示意几何均为独立制作的合成场景，不是产品录像或实测结果。',
  'play':'播放','pause':'暂停','time':'示意时间','layers':'显示图层',
  'points':'观测点','geometry':'几何表示','returns':'回波','rays':'采样射线','tracks':'轨迹',
  'hero_role':'感知算法工程师','hero_title':'从传感器观测，<br>到可用的<span>空间表示。</span>',
  'hero_intro':'我是 Merci，参与感知系统的设计、实现与量产落地，将不完美的观测转化为机器人可用的空间理解。',
  'explore':'查看精选项目','github':'GitHub 主页','hero_visual':'场景几何','hero_bottom':'观测 → 表示',
  'strip':['消费机器人','多传感器融合','C++ 工程实现'],
  'selected':'精选项目 / 01—04','work_title':'解决具体的工程问题。',
  'work_intro':'四个项目：系统全貌、工程背景与我的贡献。',
  'about_title':'感知工程实践。<br>机器人研究背景。',
  'about_p1':'目前在消费机器人领域从事感知算法工作，参与以双目或激光雷达为主要观测来源的多传感器融合感知。工作覆盖框架共同设计、模型后处理、空间理解、目标跟踪与高效 C++ 部署。',
  'about_p2':'硕士毕业于 <b>RWTH Aachen University（亚琛工业大学）</b>，专业为 <b>Robotic Systems Engineering（机器人系统工程）</b>。此前的研究经历包括碰撞检测引擎集成和基于视觉的攀岩运动分析。',
  'about_extra':'其他研究：使用小型神经网络构建制造仿真的代理模型，并配合交互式界面。',
  'toolkit':[('工程实现','C++ · Python · CMake<br>性能分析与耗时优化'),('感知','OpenCV · 点云<br>几何、语义与跟踪'),('仿真','碰撞检测<br>空间层次结构与引擎集成')],
  'contact_title':'交流工程问题。','contact_copy':'感知、几何，以及在实际环境中工作的系统。',
  'footer':'Merci · 感知与仿真','email':'邮箱',
  'notfound':'页面不存在。','return':'返回作品集',
 }
}

PROJECT_META = [('stereo','01',''),('lidar','02','blue'),('collision','03','gold'),('motion','04','purple')]
from case_content import PROJECTS
