"""Public portfolio text. English and Chinese share the same project scope."""
UI = {
 'en': {
  'work':'Work','about':'About','contact':'Contact','skip':'Skip to content','nav':'Main navigation',
  'language':'Language','back':'All selected work','role':'MY ROLE','context':'CONTEXT',
  'previous':'Previous case','next':'Next case','read':'Read case study','problem':'The problem',
  'method':'Method','choices':'Engineering choices','result':'Result & boundaries',
  'demo':'Explore the concept','synthetic':'Synthetic illustration',
  'notice':'All visuals are independently created conceptual illustrations using synthetic data. They do not show internal implementations, product recordings or measured research results.',
  'play':'Play','pause':'Pause','time':'Demonstration time','layers':'Visualization layers',
  'points':'Observations','geometry':'Geometry','returns':'Returns','rays':'Sampled rays','tracks':'Track',
  'hero_role':'Perception Algorithm Engineer','hero_title':'From observations<br>to <span>geometry.</span>',
  'hero_intro':'I’m Merci. I build perception software that turns imperfect sensor observations into useful geometry for robots.',
  'explore':'Explore selected work','github':'GitHub profile','hero_visual':'Scene geometry','hero_bottom':'Observations → representation',
  'strip':['Consumer robotics','Multi-sensor fusion','C++ implementation'],
  'selected':'Selected work / 01—04','work_title':'Engineering in practice.',
  'work_intro':'Four cases, from sparse observations to systems integration.',
  'about_title':'Perception engineer.<br>Robotics background.',
  'about_p1':'I work in consumer robotics, developing multi-sensor perception with stereo or LiDAR as the leading observation source. My work spans geometric reasoning, model post-processing, tracking and efficient C++ implementation.',
  'about_p2':'I hold an M.Sc. in <b>Robotic Systems Engineering</b> from <b>RWTH Aachen University</b>. Earlier research involved collision-engine integration and vision-based climbing analysis.',
  'about_extra':'Additional research: a small neural-network surrogate for manufacturing simulation, paired with an interactive interface.',
  'toolkit':[('Implementation','C++ · Python · CMake<br>Profiling & runtime optimization'),('Perception','OpenCV · Point clouds<br>Geometry, semantics & tracking'),('Simulation','Collision detection<br>Spatial hierarchies & integration')],
  'contact_title':'Let’s talk engineering.','contact_copy':'Perception, geometry and systems that work in practice.',
  'footer':'Merci · Perception & simulation','email':'Email',
  'notfound':'Page not found.','return':'Return to the portfolio',
 },
 'zh': {
  'work':'项目','about':'关于','contact':'联系','skip':'跳到正文','nav':'主导航',
  'language':'语言','back':'查看全部项目','role':'我的职责','context':'项目背景',
  'previous':'上一个案例','next':'下一个案例','read':'阅读案例','problem':'问题背景',
  'method':'方法思路','choices':'工程取舍','result':'结果与边界',
  'demo':'交互示意','synthetic':'合成示意',
  'notice':'所有图示均为独立制作的概念示意，使用合成数据，不展示内部实现、产品录像或实测研究结果。',
  'play':'播放','pause':'暂停','time':'示意时间','layers':'显示图层',
  'points':'观测点','geometry':'几何表示','returns':'回波','rays':'采样射线','tracks':'轨迹',
  'hero_role':'感知算法工程师','hero_title':'从传感器观测<br>到<span>可用几何。</span>',
  'hero_intro':'我是 Merci。我开发机器人感知软件，将不完美的传感器观测转化为机器人可用的几何表示。',
  'explore':'查看精选项目','github':'GitHub 主页','hero_visual':'场景几何','hero_bottom':'观测 → 表示',
  'strip':['消费机器人','多传感器融合','C++ 工程实现'],
  'selected':'精选项目 / 01—04','work_title':'解决具体的工程问题。',
  'work_intro':'四个案例：从稀疏观测到系统集成。',
  'about_title':'感知工程实践。<br>机器人研究背景。',
  'about_p1':'目前在消费机器人领域从事感知算法工作，参与以双目或 LiDAR 为主要观测来源的多传感器融合感知。工作涉及几何推理、模型后处理、目标跟踪与高效 C++ 实现。',
  'about_p2':'硕士毕业于 <b>RWTH Aachen University（亚琛工业大学）</b>，专业为 <b>Robotic Systems Engineering（机器人系统工程）</b>。此前的研究经历包括碰撞检测引擎集成和基于视觉的攀岩运动分析。',
  'about_extra':'其他研究：使用小型神经网络构建制造仿真的代理模型，并配合交互式界面。',
  'toolkit':[('工程实现','C++ · Python · CMake<br>性能分析与耗时优化'),('感知','OpenCV · 点云<br>几何、语义与跟踪'),('仿真','碰撞检测<br>空间层次结构与引擎集成')],
  'contact_title':'交流工程问题。','contact_copy':'感知、几何，以及在实际环境中工作的系统。',
  'footer':'Merci · 感知与仿真','email':'邮箱',
  'notfound':'页面不存在。','return':'返回作品集',
 }
}

PROJECT_META = [('stereo','01',''),('lidar','02','blue'),('collision','03','gold'),('motion','04','purple')]
PROJECTS = {
 'en': [
  dict(name='Stereo perception', title='Turning sparse observations into usable obstacle geometry.',
   summary='Combining geometric and semantic evidence to represent thin obstacles.',topic='GEOMETRY + SEMANTICS',
   lead='A cable may be recognizable in an image but poorly represented in depth. I worked on turning that complementary evidence into useful obstacle geometry.',
   role='Thin-obstacle representation, ground estimation, floor-surface post-processing and runtime optimization.',
   context='Stereo-led multi-sensor perception in consumer robotics.',
   problem_title='The label survives. The geometry is sparse.',
   problem=['Thin obstacles can have too few valid depth observations to form a useful spatial representation. Attaching a semantic label to those few points does not address the missing geometric support.',
            'My contribution was a fusion-informed approach to constructing the representation, rather than only assigning semantics to existing points.'],
   method_title='Complementary evidence, with different responsibilities.',
   method=['Geometric observations supply spatial evidence where depth is valid. Semantic observations supply a candidate region and object interpretation. Their roles are complementary: a semantic detection is not itself a depth measurement.',
           'Combining those cues can support an obstacle representation when observed points alone are sparse. In the demo, light points are observations and the amber dashed segment is an inferred thin-obstacle representation. The distinction remains visible.'],
   flow=[('Geometric evidence','Valid depth & surface structure'),('Semantic evidence','Candidate region & interpretation'),('Obstacle representation','Observed support + inferred geometry')],
   choices_title='Reuse structure; respect uncertainty.',
   choices=[('More useful geometry, not more claimed measurements','Constructing a representation can address sparse observations, but inferred geometry should not be described as additional measured depth.'),
            ('Different modules, different evidence','I introduced disparity-based ground estimation and developed floor-surface post-processing from complementary cues. I also adapted an existing classification pipeline to stereo and optimized its runtime.')],
   result_title='Addressing a representation limitation.',
   result=['The work addressed the sparse-point limitation of thin-obstacle perception. Stereo served as the leading observation source within a multi-sensor perception system.',
           'Depth gaps and uncertain semantic observations remain relevant limitations. The demo makes the observed-versus-inferred distinction inspectable; it does not establish a detection rate or latency.'],
   caption='Top view. Surface sampling contains gaps and occlusion. Amber dashes indicate an inferred thin-obstacle representation.',
   panels=[]),
  dict(name='LiDAR perception',title='Keeping moving targets consistent across observations.',
   summary='Introducing tracking into an established outdoor perception system.',topic='TEMPORAL CONTINUITY',
   lead='Outdoor targets move between observations. I led the introduction of tracking into an existing framework, alongside implementation, maintenance and deployment fixes.',
   role='Tracking integration, implementation, maintenance and height-related deployment fixes.',
   context='LiDAR-led multi-sensor perception for an outdoor robot.',
   problem_title='A static representation meets a changing scene.',
   problem=['People and pets move through outdoor environments. Processing each observation in isolation loses the continuity needed to describe a moving target; a static scene representation alone can be insufficient.',
            'The overall architecture had been selected before I joined. I implemented and maintained the system, and led the addition of tracking to extend its handling of dynamic targets.'],
   method_title='From an observation to a state over time.',
   method=['A single observation describes what the sensor sees now. Tracking adds the question of which observations belong to the same target over time, supporting a continuous target state.',
           'Robot motion changes the viewpoint and observation coordinates. Occlusion can remove returns temporarily without proving that a target has disappeared. These are reasons to interpret current observations together with motion context and temporal information.'],
   flow=[('Current observations','Discrete returns & target evidence'),('Temporal association','Continuity with motion context'),('Target state','Position & trajectory over time')],
   choices_title='Preserve height and temporal context.',
   choices=[('An absent return is not a complete conclusion','The synthetic track shows a short occlusion and an illustrative continuation. It distinguishes current measurement from temporal inference; it does not prescribe the deployed tracker’s prediction policy.'),
            ('A flat grid can hide relevant structure','I resolved deployment issues involving height information and overhanging obstacles. Outdoor scenes required care beyond a representation influenced by indoor two-dimensional grids.')],
   result_title='A targeted extension to an operating system.',
   result=['I introduced tracking to address dynamic targets within the established framework. The contribution was integration and deployed-system engineering, rather than ownership of the original architecture.',
           'LiDAR was the leading observation source in a multi-sensor system. Supporting sensors help interpret robot motion, but neither sensor context nor tracking removes all association ambiguity during occlusion.'],
   caption='Angular samples stop at the first surface. The dotted track segment distinguishes illustrative continuity during occlusion from current returns.',panels=[]),
  dict(name='Physics simulation',title='Adding algorithm choices to a collision engine.',
   summary='Integrating SAP, a BVH midphase and GJK alongside existing algorithms.',topic='COLLISION DETECTION',
   lead='I extended an existing physics-simulation engine with collision-query capabilities, adapting established algorithms to its geometry types, interfaces and data flow.',
   role='Broadphase, midphase and narrowphase algorithm integration.',context='An existing physics-simulation engine.',
   problem_title='An algorithm has to fit the engine around it.',
   problem=['The engine offered a limited set of collision-query options. Extending it required connecting algorithm inputs and outputs to its own object representations and processing stages.',
            'The additions complemented the original choices. They did not replace the complete collision system.'],
   method_title='Three stages, three different questions.',
   method=['Sweep and Prune belongs to the broadphase: spatial bounds and their overlap help identify candidate object pairs. Candidate filtering is not yet an exact contact determination.',
           'A BVH midphase organizes finer geometry into hierarchical bounds so queries can restrict the region requiring further examination. GJK belongs to convex narrowphase queries, complementing existing algorithms including SAT.'],
   flow=[('SAP · Broadphase','Potential object pairs'),('BVH · Midphase','Relevant geometry regions'),('GJK · Narrowphase','Convex geometry query')],
   choices_title='Integration with preserved algorithm options.',
   choices=[('Adapt the boundary between stages','The host engine and reference implementations handled basic geometry types and data flow differently. I adapted representations and query interfaces so the added algorithms could participate in the engine’s processing.'),
            ('Add capabilities without discarding existing choices','Existing algorithms remained available. The engineering result was a wider set of selectable capabilities, not a claim that one algorithm universally outperforms the others.')],
   result_title='More capability, with distinct responsibilities.',
   result=['The engine gained SAP, a BVH midphase and GJK as additional options. These were integrations of established algorithms; my contribution was implementation and adaptation within the host engine.',
           'Broadphase candidates remain conservative approximations, and convex queries have geometric scope limits. The diagrams explain these responsibilities rather than replaying an internal engine execution.'],
   caption='Conceptual collision-query stages. Candidate bounds and illustrative convex shapes explain responsibilities rather than engine internals.',
   panels=[('Broadphase · SAP','Overlapping bounds identify potential pairs.'),('Midphase · BVH','Hierarchical bounds restrict the region to examine.'),('Narrowphase · GJK','A convex-geometry query addresses a finer question.')]),
  dict(name='Vision-based climbing analysis',title='A fixed wall reference for a moving camera.',
   summary='Matching changing frame contents to fixed climbing holds on a wall template.',topic='FRAME–TEMPLATE ALIGNMENT',
   lead='As the camera scans upward, each frame contains a different subset of fixed wall holds. My master’s research aligned those local observations to a common wall reference for movement analysis.',
   role='Geometric frame-to-template matching, coordinate mapping and movement analysis.',
   context='Master’s research · Robotic Systems Engineering · RWTH Aachen University.',
   problem_title='The holds stay still. The observed window changes.',
   problem=['A video frame covers only part of the climbing wall. During an upward camera scan, holds enter and leave the frame, while their positions in the wall template stay fixed.',
            'Image-coordinate motion therefore mixes camera movement with the climber’s movement. The task was to locate each frame’s observed hold pattern within the common template.'],
   method_title='Match the hold pattern, then map the observations.',
   method=['YOLO-based hold detection supplies wall features in each frame. Geometric matching relates their local arrangement to the fixed hold pattern in the wall template, identifying the observed part of the wall.',
           'The frame-to-template mapping places observations into a common reference. Combined with MediaPipe pose estimation, this supports trajectory, velocity and joint-angle analysis across frames.'],
   flow=[('Visual observations','Holds + human pose'),('Geometric matching','Frame holds → fixed template holds'),('Coordinate mapping','Observations in a common wall reference'),('Movement analysis','Trajectory, velocity & joint angles')],
   choices_title='Align the reference before interpreting movement.',
   choices=[('Changing subsets, not moving wall points','Matching must accommodate different visible subsets. In the animation, local frame points are derived from the current window over fixed template holds; correspondences change as the window moves.'),
            ('A common reference is not a full 3D reconstruction','Alignment separates camera framing from movement in the wall reference. Monocular depth ambiguity still limits interpretation of motion away from the wall.')],
   result_title='Movement compared in the same reference.',
   result=['The alignment established a common wall reference for trajectory and velocity analysis despite camera movement. The original research videos are unavailable, so the scene uses a constructed wall and movement sequence.',
           'The speed plot is computed from that same synthetic trajectory in normalized wall coordinates. Its horizontal axis is synthetic time; it illustrates consistency between views rather than experimental measurement accuracy.'],
   caption='Fixed wall holds, an upward-moving observation window and changing frame–template correspondences. Speed is derived from the same synthetic trajectory.',
   panels=[('Current frame','Only holds inside the current window are visible.'),('Fixed wall template','The window moves upward; hold coordinates stay fixed.'),('Aligned movement','Trajectory and speed use the common wall reference.')]),
 ],
 'zh': [
  dict(name='双目感知',title='将稀疏观测转化为可用的障碍物几何。',
   summary='结合几何与语义证据，改善细小障碍物的空间表示。',topic='几何 + 语义',
   lead='线材在图像中可能可以辨认，在深度中却只有零星有效点。我的工作重点是让这些互补证据形成机器人可用的障碍物几何。',
   role='细小障碍物表示、地面估计、地面材质后处理与耗时优化。',context='消费机器人中，以双目为主要观测来源的多传感器融合感知。',
   problem_title='语义能识别，几何却不够完整。',
   problem=['细小障碍物的有效深度点可能过于稀疏，难以形成可用的空间表示。仅给这些已有点附加语义标签，并不能解决几何支撑不足的问题。',
            '我的贡献是基于融合结果构建表示，而不只是给已有点赋予语义。'],
   method_title='互补证据承担不同职责。',
   method=['有效深度提供距离和表面结构等空间证据；语义观测提供候选区域和物体解释。两者可以互补，但语义检测本身不等于深度测量。',
           '当观测点不足时，结合这些线索可以支持障碍物表示的构建。示意中浅色点表示观测，橙黄色虚线表示推断得到的细小障碍物几何，两者保持区分。'],
   flow=[('几何证据','有效深度与表面结构'),('语义证据','候选区域与物体解释'),('障碍物表示','观测支撑 + 推断几何')],
   choices_title='利用已有结构，同时保留不确定性。',
   choices=[('表示更可用，不等于测量更多','构建几何表示可以缓解观测稀疏的问题，但推断部分不能被描述为新增的实测深度。'),
            ('不同模块采用不同证据','我引入了基于视差的地面估计，开发了融合多类线索的地面材质后处理；还将已有分类流程适配到双目输入，并优化耗时。')],
   result_title='解决空间表示中的具体缺口。',
   result=['这项工作针对线材感知中的稀疏点限制，双目作为多传感器融合系统中的主要观测来源。',
           '深度缺失和语义不确定性仍然需要考虑。交互示意帮助区分观测与推断，不用于证明检出率或运行耗时。'],
   caption='俯视图。表面采样存在缺失与遮挡；橙黄色虚线表示推断得到的细小障碍物几何。',panels=[]),
  dict(name='LiDAR 感知',title='让动态目标在连续观测中保持一致。',
   summary='在既有户外感知框架中主导引入目标跟踪。',topic='时间连续性',
   lead='户外目标会在相邻观测间移动。我主导在已有框架中引入跟踪，同时承担实现、维护与实际部署问题的解决。',
   role='跟踪集成、实现维护，以及与高度信息有关的部署问题处理。',context='户外机器人中，以 LiDAR 为主要观测来源的多传感器融合感知。',
   problem_title='静态表示面对持续变化的场景。',
   problem=['庭院里的人和宠物会移动。逐帧独立处理会丢失描述动态目标所需的连续性，仅依靠静态场景表示也可能不足。',
            '整体架构在我入职前已经确定。我负责实现与维护，并主导加入跟踪能力，扩展系统对动态目标的处理。'],
   method_title='从当前观测，走向随时间变化的状态。',
   method=['单帧观测描述传感器此刻看到了什么；跟踪进一步判断连续观测中哪些属于同一个目标，从而支持持续的目标状态。',
           '机器人自身运动会改变视角和观测坐标；遮挡则可能暂时移除回波，却不能直接证明目标已经消失。这些因素要求结合运动背景与时间信息解释当前观测。'],
   flow=[('当前观测','离散回波与目标证据'),('跨帧关联','结合运动背景保持连续性'),('目标状态','随时间变化的位置与轨迹')],
   choices_title='同时保留时间与高度信息。',
   choices=[('没有回波，不足以下完整结论','合成轨迹展示了短时遮挡与示意性延续，区分当前测量和时间推断；它不规定产品跟踪器的预测策略。'),
            ('平面栅格可能隐藏重要结构','我处理过高度信息和悬空障碍物相关的部署问题。户外场景需要超出受室内二维栅格思路影响的表示方式。')],
   result_title='在运行中的系统里补充能力。',
   result=['我在既有框架内引入跟踪，针对动态目标补充时间维度的处理能力。贡献主要是模块集成和部署工程，并非原始架构的设计。',
           'LiDAR 是多传感器系统中的主要观测来源。辅助传感器有助于理解机器人自身运动，但运动背景和跟踪都不能消除所有遮挡期间的关联歧义。'],
   caption='角度采样在第一处表面停止；轨迹中的虚线区分遮挡期间的示意延续与当前回波。',panels=[]),
  dict(name='物理仿真',title='为碰撞检测引擎增加算法选择。',
   summary='在保留已有算法的同时，集成 SAP、BVH 中间阶段和 GJK。',topic='碰撞检测',
   lead='我为既有物理仿真引擎扩展碰撞查询能力，将成熟算法适配到引擎的几何类型、接口和数据流。',
   role='碰撞检测 broadphase、midphase 和 narrowphase 的算法集成。',context='一个既有的物理仿真引擎。',
   problem_title='算法需要适配周围的引擎。',
   problem=['原有引擎的碰撞查询选项较为有限。增加算法，需要把输入输出连接到引擎自己的对象表示与处理阶段。',
            '新功能与原有选择并存，没有整体替换碰撞检测系统。'],
   method_title='三个阶段，回答不同的问题。',
   method=['Sweep and Prune（SAP）用于 broadphase：利用空间包围范围及其重叠筛选候选对象对。候选筛选还不是精确接触判定。',
           'BVH midphase 将更细的几何组织为层次包围结构，缩小需要进一步检查的区域；GJK 用于凸几何 narrowphase 查询，与包括 SAT 在内的原有算法互补。'],
   flow=[('SAP · 广阶段','潜在碰撞对象对'),('BVH · 中间阶段','相关几何区域'),('GJK · 窄阶段','凸几何查询')],
   choices_title='适配接口，并保留已有选择。',
   choices=[('处理阶段之间的适配','宿主引擎与参考实现的基础几何类型、数据流处理存在差异。我适配了表示与查询接口，让新算法能够参与引擎的处理流程。'),
            ('增加能力，而非取消原有算法','已有算法仍可使用。结果是提供更多可选能力，不意味着某个算法在所有场景里都更优。')],
   result_title='职责清晰的能力扩展。',
   result=['引擎增加了 SAP、BVH midphase 和 GJK 选项。这些是成熟算法的集成；我的贡献在于实现与宿主引擎适配。',
           '广阶段候选仍是保守近似，凸几何查询也有适用范围。图示用于解释各阶段职责，而非重放内部引擎执行过程。'],
   caption='碰撞查询阶段的概念示意：用候选包围范围和凸几何解释职责。',
   panels=[('广阶段 · SAP','包围范围重叠，筛选潜在对象对。'),('中间阶段 · BVH','层次包围结构缩小待检查区域。'),('窄阶段 · GJK','凸几何查询回答更细的碰撞问题。')]),
  dict(name='视觉攀岩分析',title='为移动的镜头建立固定墙面参考。',
   summary='将画面中变化的抓手子集，对应到固定墙面模板。',topic='画面—模板对齐',
   lead='镜头向上扫描时，每帧包含的是固定墙点的不同子集。我的硕士研究将局部观测对齐到统一墙面参考，再进行运动分析。',
   role='画面到模板的几何匹配、坐标映射与运动分析。',context='硕士研究 · 机器人系统工程 · RWTH Aachen University。',
   problem_title='抓手不动，变化的是观察窗口。',
   problem=['视频画面只覆盖攀岩墙的一部分。镜头向上扫描时，抓手不断进入或离开画面，但它们在墙面模板中的位置固定。',
            '因此，图像坐标里的运动混合了镜头变化与攀岩者运动。任务是确定当前画面的抓手图案位于统一模板的哪一部分。'],
   method_title='先匹配抓手，再映射观测。',
   method=['基于 YOLO 的抓手检测提供每帧的墙面特征。几何匹配将局部排列与模板中固定的抓手图案关联，确定当前看到的墙面区域。',
           '画面到模板的映射将观测放到共同参考中。结合 MediaPipe 人体姿态估计，可以跨帧分析轨迹、速度与关节角度。'],
   flow=[('视觉观测','抓手与人体姿态'),('几何匹配','画面抓手 → 固定模板抓手'),('坐标映射','共同墙面参考中的观测'),('运动分析','轨迹、速度与关节角度')],
   choices_title='先统一参考，再解释运动。',
   choices=[('匹配变化的子集，而不是移动墙点','匹配需要适应可见抓手集合的变化。动画中的局部点由固定模板与当前观察窗口生成；窗口移动时，对应关系随可见集合更新。'),
            ('共同参考不等于完整三维重建','对齐让镜头取景变化与墙面参考中的运动得以区分，但单目深度歧义仍限制对离墙方向运动的解释。')],
   result_title='在同一个参考下比较运动。',
   result=['对齐建立了共同墙面参考，支持移动镜头视频中的轨迹与速度分析。原始研究视频已不可用，因此这里采用构造的墙面和运动序列。',
           '速度曲线由同一条合成轨迹在归一化墙面坐标中计算，横轴为示意时间。它展示不同图板之间的一致性，不代表实验测量精度。'],
   caption='固定墙点、向上移动的观察窗口，以及随可见集合变化的对应关系。速度由同一合成轨迹计算。',
   panels=[('当前画面','只显示当前窗口内可见的抓手。'),('固定墙面模板','窗口向上移动，抓手坐标保持固定。'),('对齐后的运动','轨迹与速度使用统一墙面参考。')]),
 ]
}
